version: '3.9'

services:
  postgres:
    image: postgres:17.2
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres@17:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=postgres
